### ISSUE TITLE
The Oxford-BBC Lip Reading in the Wild (LRW) Dataset

### ISSUE THREAD

**Issue by Ustelemov** [erolm-a/lip-reading#1]
Hi. Did you get access for The Oxford-BBC Lip Reading in the Wild (LRW) Dataset?

**Comment by erolm-a** [comment]
Hi. Unfortunately I have not started working on this project yet (you know, coursework, lack of time and/or knowledge and other side projects, eg. the BoydEngine), but thanks for the interest!

That said, I was looking for collaborators for the next few weeks as a break from exam reviews.

**Comment by Ustelemov** [comment]
Okay, thanks :)
